import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import Timer from 'react-timer-wrapper';
import Timecode from 'react-timecode';

export default function Home() {
  const [notifCall, setNotifCall] = useState(false);
  const [answerCall, setAnswerCall] = useState(false);

  //upcoming call notification
  function pillClick() {
    setNotifCall(notifCall => !notifCall)
  } 
  let Callin = notifCall ? 'call' : '';

  //when answer call
  function answerClick() {
    setAnswerCall(answerCall => !answerCall);
  } 
  let AnswerCall = answerCall ? 'answered' : '';

  return (
    <div className="container">
      <Head>
        <title>Dynamic Island Demo</title>
        <meta name="description" content="Generated by jefries" />
        <link rel="icon" href="/apple.ico" />
      </Head>

      <main className="main">
        <div className="screen-device">
          <Image 
            src="/bezzel-iphone.svg" 
            alt='Bezzel iPhone 14 pro' 
            layout='fill'
          />

          <div className={`status-bar ${Callin} ${AnswerCall}`}>
            <div className="clock">09:41</div>
            <div className="info-bars">
              <picture>
                <img 
                  className='connection'
                  src="/connection.svg" 
                  alt='status bar info' 
                  priority  
                  width= {16}
                  height={16}
                />
              </picture>
              <picture>
                <img 
                  className='wifi'
                  src="/wifi.svg" 
                  alt='status bar info' 
                  priority  
                  width= {21}
                  height={21}
                />
              </picture>
              <picture>
                <img 
                  className='battery'
                  src="/battery.svg" 
                  alt='status bar info' 
                  priority  
                  width= {26}
                  height={26}
                />
              </picture>
            </div>
          </div>

          <div className="notch-wrapper" onClick={pillClick}>
            <picture>
              <img 
                className="camera" 
                src="/front-camera.svg" 
                alt="front camera" 
                width='20px' height='20px'
              />
            </picture>
            <div className={`pill ${Callin} ${AnswerCall}`}>
              <div className="incoming-call">
                <div className="content-left">
                  <Image 
                    src="/tim-cook.png" 
                    alt='Tim Cook' 
                    priority  
                    width= {50}
                    height={50}
                  />
                  <div className="caller">
                    <span>iPhone</span>
                    <p>Tim Memasak</p>
                  </div>
                </div>

                <div className="content-right">
                  <div className="btn-hangup">
                    <Image 
                      src="/icon-hangup.svg" 
                      alt='Hangup Call' 
                      priority  
                      width= {20}
                      height={20}
                    />
                  </div>
                  <div className="btn-answer" onClick={answerClick}>
                    <Image 
                      src="/icon-answer.svg" 
                      alt='Answer Call' 
                      priority  
                      width= {16}
                      height={16}
                    />
                  </div>
                </div>
              </div>

              <div className='timer-countup'>
                <div className="content-left">
                  <Image 
                    src="/callup.svg" 
                    alt='Answer Call' 
                    priority  
                    width= {12}
                    height={12}
                  />
                  <div className="timer">
                    <Timer loop={true} active duration={9000}>
                      <Timecode />
                    </Timer>
                  </div>
                </div>
                <div className="content-right">
                  <Image 
                    src="/audio-apple.svg" 
                    alt='animation audio wave apple' 
                    priority  
                    width= {34}
                    height={40}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

    </div>
  )
}
